project:
  type: website
  output-dir: docs

website:
  title: "parana_2026"
  navbar:
    left:
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    lang: es



