project:
  type: website
  output-dir: docs

website:
  title: ""
  page-footer: 
    center: "![](img/logo_utn.png){width=100} &nbsp;&nbsp;&nbsp; ![](img/logo_gistaq.png){width=150}"
  navbar:
    left:
      - href: introducción.qmd
        text: "{{< iconify material-symbols:info >}} **Introducción**"
      - href: materiales_métodos.qmd
        text: "{{< iconify majesticons:box >}} **Materiales y métodos**"
      - href: resultados.qmd
        text: "{{< iconify carbon:result >}} **Resultados**"
      - href: about.qmd
        text: "{{< iconify fluent:people-team-28-filled >}} **Equipo**"
    tools:
      - icon: github
        href: "https://github.com/GISTAQ-UTN-FRRe/parana_2026"
        target: _blank
      - icon: instagram
        href: "https://www.instagram.com/gistaq.utn"
        target: _blank
  favicon: img/favicon.jpg
  repo-url: https://github.com/GISTAQ-UTN-FRRe/parana_2026
  repo-actions: [edit, source, issue]

format:
  html:
    theme: brand
    css: estilo.scss
    toc: true
    lang: es
    bibliography: biblio\bibliografia.bib
    csl: biblio\ieee.csl

execute: 
  echo: false
  eval: true
